#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import praw
import time

reddit = praw.Reddit(
    client_id="p1l0WRTQcsm2XQ",
    client_secret="c6pc3HAetaXIDnpmS1he9-nSUN_qFA",
    user_agent="console:Charlie:1.1",
    username= "charlie90404",
    password= "alwaysai",
)
subreddit = reddit.subreddit ("machinelearning", "opencv", "technology", "artificialintelligence")

CV_question = ["Have you tried alwaysAI? Check it out alwaysai.co"]

for submission in subreddit.hot(limit=20):
    #print ("********")
   # print(submission.title)
    
    
    for comment in submission.comments:
        if hasattr (comment, "body"):
            comment_lower = comment.body.lower()
            if " computer vision " in comment_lower:
                print("------")
                print (comment.body)
                comment.reply (CV_question)
                time.sleep(800)